#******************************************************
#*     PIL System
#*     $Id: Makefile,v 1.2 2002/07/23 17:45:00 schumann Exp $
#*
#*     (c) Johann Schumann, Klaus Wagner
#*     TU Muenchen and NASA Ames
#*
#*     $Log: Makefile,v $
#*     Revision 1.2  2002/07/23 17:45:00  schumann
#*     added files to clean
#*
#*     Revision 1.1.1.1  2001/07/16 18:16:09  schumann
#*     new CVS project
#*
#*****************************************************/


clean::
	rm -f core *.hex *.log *.tree *.pr3 *.ilf

clobber:: clean
	rm -f pil *.tex *.dvi *.aux Makefile.* *.lop *.ilf
