#******************************************************
#*     PIL System
#*     $Id: Makefile,v 1.1.1.1 2001/07/16 18:16:09 schumann Exp $
#*
#*     (c) Johann Schumann, Klaus Wagner
#*     TU Muenchen and NASA Ames
#*
#*     $Log: Makefile,v $
#*     Revision 1.1.1.1  2001/07/16 18:16:09  schumann
#*     new CVS project
#*
#*****************************************************/


clean::
	rm -f core

clobber:: clean
