/**************************************************/
/* w_parse1.h:  -- do not edit by hand             */
/**************************************************/

%token T_i_alloc
%token T_i_nalloc
%token T_i_dealloc
%token T_i_ndealloc
%token T_i_fold_up
%token T_i_reg_fold_up
%token T_i_call
%token T_i_stop
%token T_i_break
%token T_i_jmp
%token T_i_jmpz
%token T_i_jmpg
%token T_i_unvoid
%token T_i_unconst
%token T_i_unvar
%token T_i_ungterm
%token T_i_unngterm
%token T_i_unglobl
%token T_i_orbranch
%token T_i_porbranch
%token T_i_fail
%token T_i_reduct
%token T_i_ureduct
%token T_i_proceed
%token T_i_add
%token T_i_mul
%token T_i_sub
%token T_i_div
%token T_i_lod
%token T_i_sto
%token T_i_glod
%token T_i_gsto
%token T_i_lconst
%token T_i_assign
%token T_i_genreg
%token T_i_genxreg
%token T_i_genureg
%token T_i_cgen
%token T_i_ptree
%token T_i_out
%token T_i_tell
%token T_i_told
%token T_i_eqpred
%token T_i_eq_built
%token T_i_neq_built
%token T_i_equ_unif
%token T_i_isunifiable
%token T_i_isnotunifiable
%token T_i_pre_cut
%token T_i_cut
%token T_i_is_var
%token T_i_is_nonvar
%token T_i_is_number
%token T_i_is_const
%token T_i_is_compl
%token T_i_rand_reorder
%token T_i_setrand
%token T_i_galloc
%token T_i_size
%token T_i_tdepth
%token T_i_tdepth3
%token T_i_getdepth
%token T_i_getinf
%token T_i_getmaxinf
%token T_i_getlocinf
%token T_i_set_depth
%token T_i_set_inf
%token T_i_set_maxinf
%token T_i_set_locinf
%token T_i_functor
%token T_i_arg
%token T_i_genlemma
%token T_i_genulemma
%token T_i_checklemma
%token T_i_checkulemma
%token T_i_addtoindex
%token T_i_checkindex
%token T_i_uselemma
%token T_i_dumplemma
%token T_i_getnrlemmata
%token T_i_delrange
%token T_i_path2list
%token T_i_assume
%token T_i_init_counters
%token T_i_getcounter
%token T_i_set_counter
%token T_i_get_maxfvars
%token T_i_set_maxfvars
%token T_i_get_maxtc
%token T_i_set_maxtc
%token T_i_get_maxsgs
%token T_i_set_maxsgs
%token T_i_lpo
%token T_i_lpoeq
%token T_i_kbo
%token T_i_sig
%token T_i_precall
%token T_i_isempty
%token T_i_issubset
%token T_i_ismember
%token T_i_card
%token T_i_mkempty
%token T_i_addtoset
%token T_i_remfromset
%token T_i_selnth
%token T_i_selnext
%token T_i_postunify
%token T_i_argsize
%token T_i_preunify
%token T_i_array_assign
%token T_i_array_glod
%token T_i_array_gsto
