#******************************************************
#*     PIL System
#*     $Id: Makefile,v 1.1.1.1 2001/07/16 18:16:09 schumann Exp $
#*
#*     (c) Johann Schumann, Klaus Wagner
#*     TU Muenchen and NASA Ames
#*
#*     $Log: Makefile,v $
#*     Revision 1.1.1.1  2001/07/16 18:16:09  schumann
#*     new CVS project
#*
#*****************************************************/


clean::
	(cd bin; make clean)
	(cd lib; make clean)
	(cd src; make clean)
	(cd examples; make clean)

clobber::
	(cd bin; make clobber)
	(cd lib; make clobber)
	(cd src; make clobber)
	(cd examples; make clobber)
